-- Billing state and AI usage become server-owned (docs/decisions/006).
--
-- Before this migration a signed-in user could set their own plan to Pro, or reset their
-- AI counter, from the browser: `profiles` had table-level UPDATE and an update policy
-- with no column restriction. Plan and usage now live in tables only the service role
-- can write, and `profiles` is writable column by column.

-- subscriptions --------------------------------------------------------------
-- One row per user who has ever started a checkout. No row means the free plan.
create table public.subscriptions (
  user_id uuid primary key references public.profiles (id) on delete cascade,
  tier text not null default 'free' check (tier in ('free', 'pro')),
  status text not null default 'active' check (status in ('active', 'non_renewing', 'past_due', 'canceled')),
  plan text check (plan in ('pro_monthly', 'pro_yearly')),
  paystack_customer_code text unique,
  paystack_subscription_code text unique,
  started_at timestamptz,
  ended_at timestamptz,
  next_payment_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.subscriptions (user_id, tier, status, plan, paystack_customer_code,
  paystack_subscription_code, started_at, ended_at, next_payment_at)
select id,
  case when subscription_tier in ('pro', 'enterprise') then 'pro' else 'free' end,
  case when subscription_status in ('non_renewing', 'past_due', 'canceled') then subscription_status else 'active' end,
  subscription_plan, paystack_customer_code, paystack_subscription_code,
  subscription_started_at, subscription_ended_at, subscription_next_payment
from public.profiles
where coalesce(subscription_tier, 'free') <> 'free'
   or paystack_customer_code is not null
   or paystack_subscription_code is not null;

create trigger update_subscriptions_updated_at before update on public.subscriptions
  for each row execute function public.update_updated_at();

-- ai_runs --------------------------------------------------------------------
-- One row per model call made for a user. `units` is what the call costs against the
-- free quota (organising five items in one request is five units). Replaces
-- ai_processing_log, which users had no policy to insert into, so it never filled.
create table public.ai_runs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  operation text not null check (operation in ('organize', 'daily_plan', 'ask', 'weekly_summary')),
  units integer not null default 1 check (units > 0),
  model text,
  input_tokens integer,
  output_tokens integer,
  latency_ms integer,
  success boolean not null default true,
  error text,
  created_at timestamptz not null default now()
);
create index ai_runs_user_created_idx on public.ai_runs (user_id, created_at desc);

insert into public.ai_runs (user_id, operation, model, input_tokens, output_tokens, latency_ms, success, error, created_at)
select user_id,
  case when operation_type = 'extract_entities' then 'organize' else operation_type end,
  model_used, input_tokens, output_tokens, latency_ms, coalesce(success, true), error_message, coalesce(created_at, now())
from public.ai_processing_log;

-- Carry over what each user has already used this month, so nobody's quota resets
-- just because the counter moved.
insert into public.ai_runs (user_id, operation, units, created_at)
select p.id, 'organize', p.ai_calls_this_month - coalesce(logged.units, 0), now()
from public.profiles p
left join lateral (
  select sum(r.units) as units from public.ai_runs r
  where r.user_id = p.id and r.success and r.created_at >= date_trunc('month', now())
) logged on true
where p.ai_calls_reset_at >= date_trunc('month', now())
  and p.ai_calls_this_month - coalesce(logged.units, 0) > 0;

drop table public.ai_processing_log;

-- payment_events -------------------------------------------------------------
-- Every Paystack webhook delivery, keyed so a retried delivery is applied once.
-- Paystack sends no event id, so the key is the SHA-256 of the signed request body:
-- a retry carries the same bytes.
create table public.payment_events (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  event_type text not null,
  payload jsonb not null,
  received_at timestamptz not null default now(),
  processed_at timestamptz
);

-- profiles: billing and usage columns go; what is left is the user's own -----
alter table public.profiles
  drop column subscription_tier,
  drop column subscription_status,
  drop column subscription_plan,
  drop column subscription_started_at,
  drop column subscription_ended_at,
  drop column subscription_next_payment,
  drop column paystack_customer_code,
  drop column paystack_subscription_code,
  drop column ai_calls_this_month,
  drop column ai_calls_reset_at;

-- privileges -----------------------------------------------------------------
-- Supabase grants everything on new public tables to anon and authenticated by
-- default and leaves the rest to row level security. For server-owned tables the
-- grant itself is removed, so a careless policy later cannot reopen them.
revoke all on public.subscriptions, public.ai_runs, public.payment_events from anon, authenticated;
grant select on public.subscriptions, public.ai_runs to authenticated;

revoke all on public.payment_transactions from anon, authenticated;
grant select on public.payment_transactions to authenticated;

revoke all on public.profiles from anon, authenticated;
grant select on public.profiles to authenticated;
grant update (full_name, avatar_url, timezone, daily_plan_time, weekly_summary_day)
  on public.profiles to authenticated;

-- row level security ---------------------------------------------------------
alter table public.subscriptions enable row level security;
alter table public.ai_runs enable row level security;
alter table public.payment_events enable row level security;

create policy "Users can view own subscription" on public.subscriptions
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users can view own AI runs" on public.ai_runs
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "No client access to payment events" on public.payment_events
  for all to anon, authenticated using (false) with check (false);

drop policy "Users can update own profile" on public.profiles;
create policy "Users can update own profile" on public.profiles
  for update to authenticated
  using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

-- quota ----------------------------------------------------------------------
-- Units of successful AI work since the start of the current calendar month in the
-- user's own timezone, so the quota resets at their midnight on the 1st, not UTC's.
-- Runs with the caller's rights: a user can only ever count their own runs.
create function public.ai_units_this_month(p_user_id uuid, p_now timestamptz default now())
returns integer language sql stable set search_path = '' as $$
  select coalesce(sum(r.units), 0)::integer
  from public.ai_runs r
  cross join (
    select coalesce(
      (select n.name from public.profiles p
         join pg_catalog.pg_timezone_names n on n.name = p.timezone
        where p.id = p_user_id),
      'UTC') as name
  ) tz
  where r.user_id = p_user_id
    and r.success
    and r.created_at >= (date_trunc('month', p_now at time zone tz.name) at time zone tz.name)
    and r.created_at <= p_now
$$;
revoke execute on function public.ai_units_this_month(uuid, timestamptz) from public, anon;
grant execute on function public.ai_units_this_month(uuid, timestamptz) to authenticated, service_role;

-- advisor findings -----------------------------------------------------------
-- Pin search_path on every function and stop the API roles calling trigger functions
-- directly (they are SECURITY DEFINER and were exposed as RPC endpoints).
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'),
    new.raw_user_meta_data ->> 'avatar_url'
  );
  return new;
end;
$$;

create or replace function public.update_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.update_project_counts()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if tg_op = 'UPDATE' and old.project_id is distinct from new.project_id and old.project_id is not null then
    update public.projects set
      item_count = (select count(*) from public.inbox_items where project_id = old.project_id),
      completed_count = (select count(*) from public.inbox_items where project_id = old.project_id and status = 'completed')
    where id = old.project_id;
  end if;
  if new.project_id is not null then
    update public.projects set
      item_count = (select count(*) from public.inbox_items where project_id = new.project_id),
      completed_count = (select count(*) from public.inbox_items where project_id = new.project_id and status = 'completed')
    where id = new.project_id;
  end if;
  return new;
end;
$$;

revoke execute on function public.handle_new_user() from public, anon, authenticated;
revoke execute on function public.update_updated_at() from public, anon, authenticated;
revoke execute on function public.update_project_counts() from public, anon, authenticated;
